### ISSUE TITLE
Hanging when trying to `compute_digest`

### ISSUE THREAD

**Issue by paulyoung** [PassFort/http-signatures#17]
Hi, and thanks for producing this crate. I've actually been using @dskyberg's [fork](https://github.com/dskyberg/http-signatures/tree/ietf-httpbis-skyberg) but I've been able to reproduce my issue in this version as well.

I'm seeing a problem when I try to `sign` a `reqwest::blocking::Reqwest`. The first request I sign works as expected but the second one hangs.

At first I thought it was something to do with it being a subsequent request but now I suspect it's something about the request itself.

I'm using the default `SigningConfig` which sets `compute_digest: true`. Things work as expected if I set it to `false`.

I've tracked the problem down to this line and I'm about to try and investigate further.

https://github.com/PassFort/http-signatures/blob/c4a193fcd9982de92c99dc5f6adb3915daad135d/src/reqwest_impls.rs#L58

**Comment by paulyoung** [comment]
The [docs](https://docs.rs/reqwest/0.11.12/reqwest/blocking/struct.Body.html#method.buffer) say:

> Be aware that for large requests this method is expensive and may cause your program to run out of memory.

**Comment by paulyoung** [comment]
For what it's worth, I tried this instead and it didn't hang.

```rust
let bytes_to_digest = self.body_mut().as_mut()?.as_bytes()?;
```

The [docs for `buffer`](https://docs.rs/reqwest/0.11.12/reqwest/blocking/struct.Body.html#method.buffer) say:

> Converts streamed requests to their buffered equivalent and returns a reference to the buffer. If the request is already buffered, this has no effect.

The [docs for `as_bytes`](https://docs.rs/reqwest/0.11.12/reqwest/blocking/struct.Body.html#method.as_bytes) say:

> Returns the body as a byte slice if the body is already buffered in memory. For streamed requests this method returns `None`.

So, this is a bit confusing because the fact that `as_bytes` worked suggests that the body is already buffered into memory, and therefore `buffer` should have had no effect.

**Comment by paulyoung** [comment]
As an aside; I just noticed that the `Content-Digest` header isn't present in the first request that did succeed, according to my server.

**Comment by paulyoung** [comment]
For the first request, `self.body_mut()` is `None` and that's to be expected in this case. I'm not sure if that explains the missing digest header.

**Comment by paulyoung** [comment]
For the second request it's `Some(Body { kind: Reader { length: Unknown }})`

Perhaps the crate I'm using to create the request needs to use [`Body::sized`](https://docs.rs/reqwest/0.11.12/reqwest/blocking/struct.Body.html#method.sized)?

**Comment by paulyoung** [comment]
> So, this is a bit confusing because the fact that `as_bytes` worked suggests that the body is already buffered into memory, and therefore `buffer` should have had no effect.

On closer inspection, `as_bytes` returns `None` so I think that explains that at least.

**Comment by paulyoung** [comment]
> The [docs](https://docs.rs/reqwest/0.11.12/reqwest/blocking/struct.Body.html#method.buffer) say:
>
>> Be aware that for large requests this method is expensive and may cause your program to run out of memory.

The body for the problematic request is only 76 bytes. It's contents are:

```
0014command=ls-refs\n001bagent=git/oxide-0.21.0\n0001000csymrefs\n0009peel\n0000
```

**Comment by Diggsey** [comment]
How are you providing the request body to reqwest? If the call to `buffer()` is hanging, then it means that reading the request body hangs.

**Comment by paulyoung** [comment]
The code which does that is here: 

https://github.com/Byron/gitoxide/blob/93f2dd8f7db87afc04a523458faaa46f9b33f21a/git-transport/src/client/blocking_io/http/reqwest.rs#L50

**Comment by Byron** [comment]
After reading up on this issue, two comments seemed oddly familiar from my time debugging [a seemingly similar hanging issue in reqwest](https://github.com/seanmonstar/reqwest/issues/1646).

> I'm seeing a problem when I try to sign a reqwest::blocking::Reqwest. The first request I sign works as expected but the second one hangs.

> For the second request it's Some(Body { kind: Reader { length: Unknown }})

The attached issue shows that reqwest can hang if the content-length is larger than the actual content. Maybe it's entirely unrelated here, but that's all I know for now. My guess is that the blocking version of `reqwest` has the potential for blocking in some situations, and that's not noticeable at least in the async version.

**Comment by paulyoung** [comment]
> The first request I sign works as expected but the second one hangs.

I think this is explained by the first request having an empty body, so reading the body wasn’t attempted.

**Comment by Byron** [comment]
On second look, it might be that this issue is actually caused by a deadlock happening within `gitoxide`, and we investigate a fix.

**Comment by paulyoung** [comment]
Closing as I believe this isn't an issue with `http-sig`, and will be fixed in `gitoxide` by https://github.com/Byron/gitoxide/pull/569

Thanks everyone.
